### ISSUE TITLE
Work now?

### ISSUE THREAD

**Issue by SatanicScripter** [R3nzTheCodeGOD/Spotify-Internal#2]
(●'◡'●)

**Comment by cemenc31** [comment]
yes uwu 👉🏻👈🏻

**Comment by R3nzTheCodeGOD** [comment]
if there is a new update and it's not working, you can wait for my update or downgrade spotify

**Comment by R3nzTheCodeGOD** [comment]
should now work with the latest Spotify version @SatanicScripter
